# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .microsoft_partner_store_apis import MicrosoftPartnerStoreApis
from .version import VERSION

__all__ = ['MicrosoftPartnerStoreApis']

__version__ = VERSION

