# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .getvversionoffersoffer_operations import GetvversionoffersofferOperations
from .getvversioncustomerscustomer_operations import GetvversioncustomerscustomerOperations
from .postvversioncustomerscustomer_operations import PostvversioncustomerscustomerOperations
from .getvversioncustomersfilterfilter_operations import GetvversioncustomersfilterfilterOperations
from .deletevversioncustomerscustomer_operations import DeletevversioncustomerscustomerOperations
from .patchvversioncustomerscustomer_operations import PatchvversioncustomerscustomerOperations
from .putvversioncustomerscustomer_operations import PutvversioncustomerscustomerOperations
from .postvversiondomainsdomaincustomer_operations import PostvversiondomainsdomaincustomerOperations
from .headvversioncustomerscustomer_operations import HeadvversioncustomerscustomerOperations
from .putvversionusersuser_operations import PutvversionusersuserOperations
from .getvversionusersuser_operations import GetvversionusersuserOperations
from .getvversionofferscountrycountry_operations import GetvversionofferscountrycountryOperations
from .getvversionoffercategoriescountrycountry_operations import GetvversionoffercategoriescountrycountryOperations
from .getvversionprofileslegalbusinessvetting_versionvetting_version_operations import GetvversionprofileslegalbusinessvettingVersionvettingVersionOperations
from .getvversionprofilespartnernetworkprofilempn_idmpn_id_operations import GetvversionprofilespartnernetworkprofilempnIdmpnIdOperations
from .getvversionprofilesmpnmpn_idmpn_id_operations import GetvversionprofilesmpnmpnIdmpnIdOperations
from .getvversionrelationshipsrelationship_operations import GetvversionrelationshipsrelationshipOperations
from .getvversionrelationshipspartner_operations import GetvversionrelationshipspartnerOperations
from .patchvversionrelationshipspartner_operations import PatchvversionrelationshipspartnerOperations
from .getvversionratecardsazurecurrencycurrency_operations import GetvversionratecardsazurecurrencycurrencyOperations
from .getvversionratecardsazure_sharedcurrencycurrency_operations import GetvversionratecardsazureSharedcurrencycurrencyOperations
from .getvversioncustomersrelationshiprequestsindirect_cloud_solution_provider_idindirect_cloud_solution_provider_id_operations import GetvversioncustomersrelationshiprequestsindirectCloudSolutionProviderIdindirectCloudSolutionProviderIdOperations
from .getvversionrolesrole_operations import GetvversionrolesroleOperations
from .postvversionrolesrole_operations import PostvversionrolesroleOperations
from .deletevversionrolesrole_operations import DeletevversionrolesroleOperations
from .getvversionserviceincidentsofficefilterfilter_operations import GetvversionserviceincidentsofficefilterfilterOperations
from .getvversionserviceincidentsofficecountfilterfilter_operations import GetvversionserviceincidentsofficecountfilterfilterOperations
from .getvversionservicerequestsfilterfilter_operations import GetvversionservicerequestsfilterfilterOperations
from .getvversionservicerequestsservice_operations import GetvversionservicerequestsserviceOperations
from .patchvversionservicerequestsservice_operations import PatchvversionservicerequestsserviceOperations
from .postvversionservicerequestsagent_operations import PostvversionservicerequestsagentOperations
from .getvversionvalidationscheckdomainavailabilitydomain_operations import GetvversionvalidationscheckdomainavailabilitydomainOperations

__all__ = [
    'GetvversionoffersofferOperations',
    'GetvversioncustomerscustomerOperations',
    'PostvversioncustomerscustomerOperations',
    'GetvversioncustomersfilterfilterOperations',
    'DeletevversioncustomerscustomerOperations',
    'PatchvversioncustomerscustomerOperations',
    'PutvversioncustomerscustomerOperations',
    'PostvversiondomainsdomaincustomerOperations',
    'HeadvversioncustomerscustomerOperations',
    'PutvversionusersuserOperations',
    'GetvversionusersuserOperations',
    'GetvversionofferscountrycountryOperations',
    'GetvversionoffercategoriescountrycountryOperations',
    'GetvversionprofileslegalbusinessvettingVersionvettingVersionOperations',
    'GetvversionprofilespartnernetworkprofilempnIdmpnIdOperations',
    'GetvversionprofilesmpnmpnIdmpnIdOperations',
    'GetvversionrelationshipsrelationshipOperations',
    'GetvversionrelationshipspartnerOperations',
    'PatchvversionrelationshipspartnerOperations',
    'GetvversionratecardsazurecurrencycurrencyOperations',
    'GetvversionratecardsazureSharedcurrencycurrencyOperations',
    'GetvversioncustomersrelationshiprequestsindirectCloudSolutionProviderIdindirectCloudSolutionProviderIdOperations',
    'GetvversionrolesroleOperations',
    'PostvversionrolesroleOperations',
    'DeletevversionrolesroleOperations',
    'GetvversionserviceincidentsofficefilterfilterOperations',
    'GetvversionserviceincidentsofficecountfilterfilterOperations',
    'GetvversionservicerequestsfilterfilterOperations',
    'GetvversionservicerequestsserviceOperations',
    'PatchvversionservicerequestsserviceOperations',
    'PostvversionservicerequestsagentOperations',
    'GetvversionvalidationscheckdomainavailabilitydomainOperations',
]
