# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1InternalAccountSettingsAccountSetting(Model):
    """Represents an account setting key-value pair.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param key: Gets or sets the setting key. Possible values include:
     'third_party_domain_purchases', 'public_site_purchases'
    :type key: str or ~microsoft.store.partnercenterservices.models.enum
    :param value: Gets or sets a value indicating whether the setting is
     active or not.
    :type value: bool
    :ivar attributes: Gets the attributes.
    :vartype attributes:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceAttributes
    """

    _validation = {
        'attributes': {'readonly': True},
    }

    _attribute_map = {
        'key': {'key': 'key', 'type': 'str'},
        'value': {'key': 'value', 'type': 'bool'},
        'attributes': {'key': 'attributes', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceAttributes'},
    }

    def __init__(self, key=None, value=None):
        super(MicrosoftPartnerSdkContractsV1InternalAccountSettingsAccountSetting, self).__init__()
        self.key = key
        self.value = value
        self.attributes = None
