# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkInternalContractsAnalyticsLicenseWorkload(Model):
    """Business object model that represents work loads for products.

    :param friendly_name: Workload names like sharepoint, exchange
    :type friendly_name: str
    :param licenses_active_all_channel_all_partner: Total active seats as of
     processed time stamp.
    :type licenses_active_all_channel_all_partner: long
    :param licenses_entitled_all_channel_all_partner: Total qualified
     entitlements as of processed time stamp.
    :type licenses_entitled_all_channel_all_partner: long
    :param licenses_total_sold_seats: Total sold seats per licenses as of
     processed timestamp.
    :type licenses_total_sold_seats: long
    :param active_percent: Percentage of active workload seats.
    :type active_percent: float
    """

    _attribute_map = {
        'friendly_name': {'key': 'friendlyName', 'type': 'str'},
        'licenses_active_all_channel_all_partner': {'key': 'licensesActiveAllChannelAllPartner', 'type': 'long'},
        'licenses_entitled_all_channel_all_partner': {'key': 'licensesEntitledAllChannelAllPartner', 'type': 'long'},
        'licenses_total_sold_seats': {'key': 'licensesTotalSoldSeats', 'type': 'long'},
        'active_percent': {'key': 'activePercent', 'type': 'float'},
    }

    def __init__(self, friendly_name=None, licenses_active_all_channel_all_partner=None, licenses_entitled_all_channel_all_partner=None, licenses_total_sold_seats=None, active_percent=None):
        super(MicrosoftPartnerSdkInternalContractsAnalyticsLicenseWorkload, self).__init__()
        self.friendly_name = friendly_name
        self.licenses_active_all_channel_all_partner = licenses_active_all_channel_all_partner
        self.licenses_entitled_all_channel_all_partner = licenses_entitled_all_channel_all_partner
        self.licenses_total_sold_seats = licenses_total_sold_seats
        self.active_percent = active_percent
