# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1InternalAccountRolesAccountRole(Model):
    """Represents an account role.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param value: Gets or sets the account role enum. Possible values include:
     'none', 'company', 'limited', 'limited_mpn', 'mpn', 'advisor',
     'advisor_with_dap', 'value_added_reseller', 'cloud_solution_provider',
     'distributor', 'incentive', 'referrals', 'basic_mpn', 'limited_basic_mpn',
     'publisher', 'control_panel_vendor', 'offboarding_cloud_solution_provider'
    :type value: str or ~microsoft.store.partnercenterservices.models.enum
    :ivar attributes: Gets the attributes.
    :vartype attributes:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceAttributes
    """

    _validation = {
        'attributes': {'readonly': True},
    }

    _attribute_map = {
        'value': {'key': 'value', 'type': 'str'},
        'attributes': {'key': 'attributes', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceAttributes'},
    }

    def __init__(self, value=None):
        super(MicrosoftPartnerSdkContractsV1InternalAccountRolesAccountRole, self).__init__()
        self.value = value
        self.attributes = None
