# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftMarketplaceServicesCoreServiceFault(Model):
    """MicrosoftMarketplaceServicesCoreServiceFault.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param code:
    :type code: int
    :param description:
    :type description: str
    :ivar data:
    :vartype data: list[str]
    :param source:
    :type source: str
    """

    _validation = {
        'data': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'description': {'key': 'description', 'type': 'str'},
        'data': {'key': 'data', 'type': '[str]'},
        'source': {'key': 'source', 'type': 'str'},
    }

    def __init__(self, code=None, description=None, source=None):
        super(MicrosoftMarketplaceServicesCoreServiceFault, self).__init__()
        self.code = code
        self.description = description
        self.data = None
        self.source = source
