# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1DomainManagementVerifiedDomain(Model):
    """Represents VerifiedDomain request and response.

    :param verified_domain_name: Verified Domain Name
    :type verified_domain_name: str
    :param domain: Domain
    :type domain:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1DomainManagementDomain
    :param domain_federation_settings: Domain federation settings
    :type domain_federation_settings:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1DomainManagementDomainFederationSettings
    """

    _attribute_map = {
        'verified_domain_name': {'key': 'verifiedDomainName', 'type': 'str'},
        'domain': {'key': 'domain', 'type': 'MicrosoftPartnerSdkContractsV1DomainManagementDomain'},
        'domain_federation_settings': {'key': 'domainFederationSettings', 'type': 'MicrosoftPartnerSdkContractsV1DomainManagementDomainFederationSettings'},
    }

    def __init__(self, verified_domain_name=None, domain=None, domain_federation_settings=None):
        super(MicrosoftPartnerSdkContractsV1DomainManagementVerifiedDomain, self).__init__()
        self.verified_domain_name = verified_domain_name
        self.domain = domain
        self.domain_federation_settings = domain_federation_settings
