# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1FlightInsiderProgram(Model):
    """Flight details.

    :param id: The flight name
    :type id: str
    :param name: The flight display name
    :type name: str
    :param enrollment_status: Enrollment status of the partner in the flight
    :type enrollment_status: bool
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'enrollment_status': {'key': 'enrollmentStatus', 'type': 'bool'},
    }

    def __init__(self, id=None, name=None, enrollment_status=None):
        super(MicrosoftPartnerSdkContractsV1FlightInsiderProgram, self).__init__()
        self.id = id
        self.name = name
        self.enrollment_status = enrollment_status
