# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1DomainManagementDomain(Model):
    """Represents Customer or partner's domain.

    :param authentication_type: Domain authentication type. Possible values
     include: 'managed', 'federated'
    :type authentication_type: str or
     ~microsoft.store.partnercenterservices.models.enum
    :param capability: Domain Capability. Possible values include: 'none',
     'email', 'sharepoint', 'office_communications_online',
     'sharepoint_default', 'full_redelegation', 'share_point_public',
     'org_id_authentication', 'yammer', 'intune', 'all'
    :type capability: str or
     ~microsoft.store.partnercenterservices.models.enum
    :param is_default: Is default domain?
    :type is_default: bool
    :param is_initial: Is initial domain?
    :type is_initial: bool
    :param name: Domain name
    :type name: str
    :param root_domain: Root Domain name
    :type root_domain: str
    :param status: Domain Status. Possible values include: 'unverified',
     'verified', 'pending_deletion'
    :type status: str or ~microsoft.store.partnercenterservices.models.enum
    :param verification_method: Domain Verification Method. Possible values
     include: 'none', 'dns_record', 'email'
    :type verification_method: str or
     ~microsoft.store.partnercenterservices.models.enum
    """

    _attribute_map = {
        'authentication_type': {'key': 'authenticationType', 'type': 'str'},
        'capability': {'key': 'capability', 'type': 'str'},
        'is_default': {'key': 'isDefault', 'type': 'bool'},
        'is_initial': {'key': 'isInitial', 'type': 'bool'},
        'name': {'key': 'name', 'type': 'str'},
        'root_domain': {'key': 'rootDomain', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
        'verification_method': {'key': 'verificationMethod', 'type': 'str'},
    }

    def __init__(self, authentication_type=None, capability=None, is_default=None, is_initial=None, name=None, root_domain=None, status=None, verification_method=None):
        super(MicrosoftPartnerSdkContractsV1DomainManagementDomain, self).__init__()
        self.authentication_type = authentication_type
        self.capability = capability
        self.is_default = is_default
        self.is_initial = is_initial
        self.name = name
        self.root_domain = root_domain
        self.status = status
        self.verification_method = verification_method
