# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1LinksTransferEntityLinks(Model):
    """Colleciton of links attached to a transfer entity.

    :param order: Gets or sets the order.
    :type order:
     ~azure.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonLink
    :param subscription: Gets or sets the subscription.
    :type subscription:
     ~azure.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonLink
    :param self: The self uri.
    :type self:
     ~azure.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonLink
    :param next: The next page of items.
    :type next:
     ~azure.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonLink
    :param previous: The previous page of items.
    :type previous:
     ~azure.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonLink
    """

    _attribute_map = {
        'order': {'key': 'order', 'type': 'MicrosoftPartnerSdkContractsV1CommonLink'},
        'subscription': {'key': 'subscription', 'type': 'MicrosoftPartnerSdkContractsV1CommonLink'},
        'self': {'key': 'self', 'type': 'MicrosoftPartnerSdkContractsV1CommonLink'},
        'next': {'key': 'next', 'type': 'MicrosoftPartnerSdkContractsV1CommonLink'},
        'previous': {'key': 'previous', 'type': 'MicrosoftPartnerSdkContractsV1CommonLink'},
    }

    def __init__(self, order=None, subscription=None, self=None, next=None, previous=None):
        super(MicrosoftPartnerSdkContractsV1LinksTransferEntityLinks, self).__init__()
        self.order = order
        self.subscription = subscription
        self.self = self
        self.next = next
        self.previous = previous
