# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1SubscriptionsConversion(Model):
    """Contains information used to convert a trial subscription to a paid
    subscription.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param offer_id: Gets or sets the offer identifier of the original, trial
     offer.
    :type offer_id: str
    :param target_offer_id: Gets or sets the offer identifier for the target
     offer.
    :type target_offer_id: str
    :param order_id: Gets or sets the order identifier.
    :type order_id: str
    :param quantity: Gets or sets the number of licenses.  The default is the
     number of licenses in the trial subscription.
    :type quantity: int
    :param billing_cycle: Indicates how often the partner is charged for the
     subscription. Possible values include: 'unknown', 'monthly', 'annual',
     'none', 'one_time'
    :type billing_cycle: str or
     ~microsoft.store.partnercenterservices.models.enum
    :ivar attributes: Gets the attributes.
    :vartype attributes:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceAttributes
    """

    _validation = {
        'attributes': {'readonly': True},
    }

    _attribute_map = {
        'offer_id': {'key': 'offerId', 'type': 'str'},
        'target_offer_id': {'key': 'targetOfferId', 'type': 'str'},
        'order_id': {'key': 'orderId', 'type': 'str'},
        'quantity': {'key': 'quantity', 'type': 'int'},
        'billing_cycle': {'key': 'billingCycle', 'type': 'str'},
        'attributes': {'key': 'attributes', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceAttributes'},
    }

    def __init__(self, offer_id=None, target_offer_id=None, order_id=None, quantity=None, billing_cycle=None):
        super(MicrosoftPartnerSdkContractsV1SubscriptionsConversion, self).__init__()
        self.offer_id = offer_id
        self.target_offer_id = target_offer_id
        self.order_id = order_id
        self.quantity = quantity
        self.billing_cycle = billing_cycle
        self.attributes = None
