# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1TransfersLastKnownBillingPeriod(Model):
    """LastKnownBillingPeriod represents billing period(start date, end date)
    information required to transfer the customer subscription.

    :param start_date: Gets or sets a value indicating the start date.
    :type start_date: datetime
    :param end_date: Gets or sets a value indicating the end date.
    :type end_date: datetime
    """

    _attribute_map = {
        'start_date': {'key': 'startDate', 'type': 'iso-8601'},
        'end_date': {'key': 'endDate', 'type': 'iso-8601'},
    }

    def __init__(self, start_date=None, end_date=None):
        super(MicrosoftPartnerSdkContractsV1TransfersLastKnownBillingPeriod, self).__init__()
        self.start_date = start_date
        self.end_date = end_date
