# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1RelationshipRequest(Model):
    """Represents a relationship request. Provides the URL by which a customer can
    establish a relationship with a partner.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param url: Gets or sets the relationship request URL.
    :type url: str
    :ivar attributes: Gets the attributes.
    :vartype attributes:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceAttributes
    """

    _validation = {
        'attributes': {'readonly': True},
    }

    _attribute_map = {
        'url': {'key': 'url', 'type': 'str'},
        'attributes': {'key': 'attributes', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceAttributes'},
    }

    def __init__(self, url=None):
        super(MicrosoftPartnerSdkContractsV1RelationshipRequest, self).__init__()
        self.url = url
        self.attributes = None
