# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1DomainManagementSigningCertificateUpdateStatus(Model):
    """Represents Signing Certificate Update Status.

    :param last_run_at: Last Run At
    :type last_run_at: datetime
    :param result: Result
    :type result: int
    """

    _attribute_map = {
        'last_run_at': {'key': 'lastRunAt', 'type': 'iso-8601'},
        'result': {'key': 'result', 'type': 'int'},
    }

    def __init__(self, last_run_at=None, result=None):
        super(MicrosoftPartnerSdkContractsV1DomainManagementSigningCertificateUpdateStatus, self).__init__()
        self.last_run_at = last_run_at
        self.result = result
