# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1TransfersTransfer(Model):
    """Transfer represents information required to transfer a
    subscription(EA/Direct)[or in the future - customer/asset].

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param transfer_type: The transfer entity type. Possible values include:
     'none', 'subscription', 'customer', 'asset'
    :type transfer_type: str or
     ~microsoft.store.partnercenterservices.models.enum
    :param transfer_entity: The transfer entity.
    :type transfer_entity:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1TransfersTransferEntity
    :param id: The transfer identifier.
    :type id: str
    :param state: The transfer state. Possible values include: 'none',
     'in_progress', 'active', 'decline', 'expired', 'revoked', 'completed'
    :type state: str or ~microsoft.store.partnercenterservices.models.enum
    :param creation_date: The creation date of the transfer
    :type creation_date: datetime
    :param expiration_date: The expiration date of the transfer
    :type expiration_date: datetime
    :param links: Gets or sets the links.
    :type links:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceLinks
    :ivar attributes: Gets the attributes.
    :vartype attributes:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceAttributes
    """

    _validation = {
        'attributes': {'readonly': True},
    }

    _attribute_map = {
        'transfer_type': {'key': 'transferType', 'type': 'str'},
        'transfer_entity': {'key': 'transferEntity', 'type': 'MicrosoftPartnerSdkContractsV1TransfersTransferEntity'},
        'id': {'key': 'id', 'type': 'str'},
        'state': {'key': 'state', 'type': 'str'},
        'creation_date': {'key': 'creationDate', 'type': 'iso-8601'},
        'expiration_date': {'key': 'expirationDate', 'type': 'iso-8601'},
        'links': {'key': 'links', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceLinks'},
        'attributes': {'key': 'attributes', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceAttributes'},
    }

    def __init__(self, transfer_type=None, transfer_entity=None, id=None, state=None, creation_date=None, expiration_date=None, links=None):
        super(MicrosoftPartnerSdkContractsV1TransfersTransfer, self).__init__()
        self.transfer_type = transfer_type
        self.transfer_entity = transfer_entity
        self.id = id
        self.state = state
        self.creation_date = creation_date
        self.expiration_date = expiration_date
        self.links = links
        self.attributes = None
