# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1CommonLink(Model):
    """Link represents a URI and the HTTP method which indicates the desired
    action for accessing the resource.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar uri: The URI.
    :vartype uri: str
    :ivar method: The method.
    :vartype method: str
    :ivar headers: Gets the link headers.
    :vartype headers:
     list[~microsoft.store.partnercenterservices.models.SystemCollectionsGenericKeyValuePairSystemStringSystemString]
    """

    _validation = {
        'uri': {'readonly': True},
        'method': {'readonly': True},
        'headers': {'readonly': True},
    }

    _attribute_map = {
        'uri': {'key': 'uri', 'type': 'str'},
        'method': {'key': 'method', 'type': 'str'},
        'headers': {'key': 'headers', 'type': '[SystemCollectionsGenericKeyValuePairSystemStringSystemString]'},
    }

    def __init__(self):
        super(MicrosoftPartnerSdkContractsV1CommonLink, self).__init__()
        self.uri = None
        self.method = None
        self.headers = None
