# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1UserLicenseManagementLicenseWarning(Model):
    """Contains warning information that occurred during a license update
    operation.

    :param code: Gets or sets the warning code.
    :type code: str
    :param message: Gets or sets the warning message.
    :type message: str
    :param service_plans: Gets or sets the list of service plan names
     associated with the warning.
    :type service_plans: list[str]
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'service_plans': {'key': 'servicePlans', 'type': '[str]'},
    }

    def __init__(self, code=None, message=None, service_plans=None):
        super(MicrosoftPartnerSdkContractsV1UserLicenseManagementLicenseWarning, self).__init__()
        self.code = code
        self.message = message
        self.service_plans = service_plans
