# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1UserLicenseManagementLicenseAssignment(Model):
    """Provides the information needed for a license update operation.

    :param excluded_plans: Gets or sets the service plan identifiers to be
     excluded from availability to the user.
    :type excluded_plans: list[str]
    :param sku_id: Gets or sets the product SKU identifier for the license.
    :type sku_id: str
    """

    _attribute_map = {
        'excluded_plans': {'key': 'excludedPlans', 'type': '[str]'},
        'sku_id': {'key': 'skuId', 'type': 'str'},
    }

    def __init__(self, excluded_plans=None, sku_id=None):
        super(MicrosoftPartnerSdkContractsV1UserLicenseManagementLicenseAssignment, self).__init__()
        self.excluded_plans = excluded_plans
        self.sku_id = sku_id
