# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1TransfersTransferEntity(Model):
    """TransferEntity represents collection of information required to transfer a
    subscription(EA/Direct).

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param id: The transfer entity identifier.
    :type id: str
    :param name: Gets or sets the source The transfer entity name.
    :type name: str
    :param current_owner: Gets or sets the current owner identifier of the
     transfer entity
    :type current_owner: str
    :param customer_id: Gets or sets the customer identifier
    :type customer_id: str
    :param transfer_type: The transfer entity type. Possible values include:
     'none', 'subscription', 'customer', 'asset'
    :type transfer_type: str or
     ~microsoft.store.partnercenterservices.models.enum
    :param billing_details: Gets or sets the billing details for the
     subscription.
    :type billing_details:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1TransfersLastKnownBillingDetails
    :param transfer_entity_links: Gets or sets the transfer entity linkes.
    :type transfer_entity_links:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1LinksTransferEntityLinks
    :param properties: Gets or sets the properties. In the future, any
     properties that are used internally should be put in this property bag.
    :type properties: dict[str, str]
    :ivar attributes: Gets the attributes.
    :vartype attributes:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceAttributes
    """

    _validation = {
        'attributes': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'current_owner': {'key': 'currentOwner', 'type': 'str'},
        'customer_id': {'key': 'customerID', 'type': 'str'},
        'transfer_type': {'key': 'transferType', 'type': 'str'},
        'billing_details': {'key': 'billingDetails', 'type': 'MicrosoftPartnerSdkContractsV1TransfersLastKnownBillingDetails'},
        'transfer_entity_links': {'key': 'transferEntityLinks', 'type': 'MicrosoftPartnerSdkContractsV1LinksTransferEntityLinks'},
        'properties': {'key': 'properties', 'type': '{str}'},
        'attributes': {'key': 'attributes', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceAttributes'},
    }

    def __init__(self, id=None, name=None, current_owner=None, customer_id=None, transfer_type=None, billing_details=None, transfer_entity_links=None, properties=None):
        super(MicrosoftPartnerSdkContractsV1TransfersTransferEntity, self).__init__()
        self.id = id
        self.name = name
        self.current_owner = current_owner
        self.customer_id = customer_id
        self.transfer_type = transfer_type
        self.billing_details = billing_details
        self.transfer_entity_links = transfer_entity_links
        self.properties = properties
        self.attributes = None
