# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1ContractsConnectUsScenario(Model):
    """Represent the Connect Us Scenario object.

    :param name: Gets or sets the name.
    :type name: str
    :param code: Gets or sets the code.
    :type code: int
    :param consultation_types: Gets or sets the consultation types.
    :type consultation_types:
     list[~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1ContractsConnectUsConsultationType]
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'code': {'key': 'code', 'type': 'int'},
        'consultation_types': {'key': 'consultationTypes', 'type': '[MicrosoftPartnerSdkContractsV1ContractsConnectUsConsultationType]'},
    }

    def __init__(self, name=None, code=None, consultation_types=None):
        super(MicrosoftPartnerSdkContractsV1ContractsConnectUsScenario, self).__init__()
        self.name = name
        self.code = code
        self.consultation_types = consultation_types
