# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1PartnerUserProfile(Model):
    """Base partner user profile.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar profile_type: Gets the profile type. Possible values include:
     'none', 'certification', 'assessment'
    :vartype profile_type: str or
     ~microsoft.store.partnercenterservices.models.enum
    :ivar attributes: Gets the attributes.
    :vartype attributes:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceAttributes
    """

    _validation = {
        'profile_type': {'readonly': True},
        'attributes': {'readonly': True},
    }

    _attribute_map = {
        'profile_type': {'key': 'profileType', 'type': 'str'},
        'attributes': {'key': 'attributes', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceAttributes'},
    }

    def __init__(self):
        super(MicrosoftPartnerSdkContractsV1PartnerUserProfile, self).__init__()
        self.profile_type = None
        self.attributes = None
