# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsAnalyticsPartnerLicensesDeploymentInsights(Model):
    """Contains partner level insights about license deployment.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param prorated_deployment_percent: The percentage of licenses deployed by
     customers of this partner.
    :type prorated_deployment_percent: float
    :param licenses_sold: The number of licenses sold.
    :type licenses_sold: long
    :param processed_date_time: The date and time when the data was
     aggregated.
    :type processed_date_time: datetime
    :param service_code: The service code of the license.
    :type service_code: str
    :param service_name: The service name. (Example : Office, CRM)
    :type service_name: str
    :param channel: The channel name of the service. (Example : reseller)
    :type channel: str
    :ivar attributes: Gets the attributes.
    :vartype attributes:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceAttributes
    """

    _validation = {
        'attributes': {'readonly': True},
    }

    _attribute_map = {
        'prorated_deployment_percent': {'key': 'proratedDeploymentPercent', 'type': 'float'},
        'licenses_sold': {'key': 'licensesSold', 'type': 'long'},
        'processed_date_time': {'key': 'processedDateTime', 'type': 'iso-8601'},
        'service_code': {'key': 'serviceCode', 'type': 'str'},
        'service_name': {'key': 'serviceName', 'type': 'str'},
        'channel': {'key': 'channel', 'type': 'str'},
        'attributes': {'key': 'attributes', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceAttributes'},
    }

    def __init__(self, prorated_deployment_percent=None, licenses_sold=None, processed_date_time=None, service_code=None, service_name=None, channel=None):
        super(MicrosoftPartnerSdkContractsAnalyticsPartnerLicensesDeploymentInsights, self).__init__()
        self.prorated_deployment_percent = prorated_deployment_percent
        self.licenses_sold = licenses_sold
        self.processed_date_time = processed_date_time
        self.service_code = service_code
        self.service_name = service_name
        self.channel = channel
        self.attributes = None
