# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1ContractsConnectUsLanguage(Model):
    """Represent the Connect Us Language object.

    :param iso_code: Gets or sets the ISO code.
    :type iso_code: str
    :param name: Gets or sets the name.
    :type name: str
    """

    _attribute_map = {
        'iso_code': {'key': 'isoCode', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
    }

    def __init__(self, iso_code=None, name=None):
        super(MicrosoftPartnerSdkContractsV1ContractsConnectUsLanguage, self).__init__()
        self.iso_code = iso_code
        self.name = name
