# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1OfferCategory(Model):
    """Describes the categorization of an offer.
    This includes the rank or priority of this offer category compared to
    others in the same product line.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param id: Gets or sets the category identifier.
    :type id: str
    :param name: Gets or sets the category name.
    :type name: str
    :param rank: Gets or sets the category rank or priority compared to other
     categories in the same offer.
     This property should be set only if there is more than one offer category
     for a given offer.
    :type rank: int
    :param locale: Gets or sets the locale in which the offer category
     applies.
    :type locale: str
    :param country: Gets or sets the country/region where the offer category
     applies.
    :type country: str
    :param links: Gets or sets the links.
    :type links:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceLinks
    :ivar attributes: Gets the attributes.
    :vartype attributes:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceAttributes
    """

    _validation = {
        'attributes': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'rank': {'key': 'rank', 'type': 'int'},
        'locale': {'key': 'locale', 'type': 'str'},
        'country': {'key': 'country', 'type': 'str'},
        'links': {'key': 'links', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceLinks'},
        'attributes': {'key': 'attributes', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceAttributes'},
    }

    def __init__(self, id=None, name=None, rank=None, locale=None, country=None, links=None):
        super(MicrosoftPartnerSdkContractsV1OfferCategory, self).__init__()
        self.id = id
        self.name = name
        self.rank = rank
        self.locale = locale
        self.country = country
        self.links = links
        self.attributes = None
