# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1DeviceDeploymentDeviceUploadDetails(Model):
    """Describes the status of an upload of information about a device.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param device_id: Gets or sets a GUID-formatted string that is associated
     with the device.
    :type device_id: str
    :param serial_number: Gets or sets the serial number uniquely associated
     with the device.
    :type serial_number: str
    :param product_key: Gets or sets the product key uniquely associated with
     the device.
    :type product_key: str
    :param status: Gets or sets the status of the device information upload.
     Possible values include: 'unknown', 'queued', 'processing', 'finished',
     'finished_with_errors'
    :type status: str or ~microsoft.store.partnercenterservices.models.enum
    :param error_code: Gets or sets the HTTP status error code that is
     returned if the device upload fails.
    :type error_code: str
    :param error_description: Gets or sets the HTTP error description that is
     returned if the device upload fails.
    :type error_description: str
    :ivar attributes: Gets the attributes.
    :vartype attributes:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceAttributes
    """

    _validation = {
        'attributes': {'readonly': True},
    }

    _attribute_map = {
        'device_id': {'key': 'deviceId', 'type': 'str'},
        'serial_number': {'key': 'serialNumber', 'type': 'str'},
        'product_key': {'key': 'productKey', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
        'error_code': {'key': 'errorCode', 'type': 'str'},
        'error_description': {'key': 'errorDescription', 'type': 'str'},
        'attributes': {'key': 'attributes', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceAttributes'},
    }

    def __init__(self, device_id=None, serial_number=None, product_key=None, status=None, error_code=None, error_description=None):
        super(MicrosoftPartnerSdkContractsV1DeviceDeploymentDeviceUploadDetails, self).__init__()
        self.device_id = device_id
        self.serial_number = serial_number
        self.product_key = product_key
        self.status = status
        self.error_code = error_code
        self.error_description = error_description
        self.attributes = None
