# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1ContractsPasswordProfile(Model):
    """Describes a specific password and indicates if that password needs to be
    changed.

    :param password: Gets or sets the password.
    :type password:
     ~microsoft.store.partnercenterservices.models.SystemSecuritySecureString
    :param force_change_password: Gets or sets a value indicating whether the
     password must be forcibly changed on the next login.
    :type force_change_password: bool
    """

    _attribute_map = {
        'password': {'key': 'password', 'type': 'SystemSecuritySecureString'},
        'force_change_password': {'key': 'forceChangePassword', 'type': 'bool'},
    }

    def __init__(self, password=None, force_change_password=None):
        super(MicrosoftPartnerSdkContractsV1ContractsPasswordProfile, self).__init__()
        self.password = password
        self.force_change_password = force_change_password
