# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkInternalContractsAnalyticsPartnerLicenseRollingServiceInsights(Model):
    """Business object model that contains service rolling insights of a partner
    scoped across all customers.

    :param start_date: Rolling metrics consider the data only after this
     timestamp
    :type start_date: datetime
    :param end_date: Rolling metrics consider the data only before this
     timestamp
    :type end_date: datetime
    :param customers_count: New customer count between compute_start_time and
     compute_end_time.
    :type customers_count: long
    :param sold_seats: New sold seats count between compute_start_time and
     compute_end_time.
    :type sold_seats: long
    :param deployed_seats_all_channel_all_partner: New deployed seats count
     between compute_start_time and compute_end_time.
    :type deployed_seats_all_channel_all_partner: long
    :param subscriptions_count: New subscription count between
     compute_start_time and compute_end_time.
    :type subscriptions_count: long
    """

    _attribute_map = {
        'start_date': {'key': 'startDate', 'type': 'iso-8601'},
        'end_date': {'key': 'endDate', 'type': 'iso-8601'},
        'customers_count': {'key': 'customersCount', 'type': 'long'},
        'sold_seats': {'key': 'soldSeats', 'type': 'long'},
        'deployed_seats_all_channel_all_partner': {'key': 'deployedSeatsAllChannelAllPartner', 'type': 'long'},
        'subscriptions_count': {'key': 'subscriptionsCount', 'type': 'long'},
    }

    def __init__(self, start_date=None, end_date=None, customers_count=None, sold_seats=None, deployed_seats_all_channel_all_partner=None, subscriptions_count=None):
        super(MicrosoftPartnerSdkInternalContractsAnalyticsPartnerLicenseRollingServiceInsights, self).__init__()
        self.start_date = start_date
        self.end_date = end_date
        self.customers_count = customers_count
        self.sold_seats = sold_seats
        self.deployed_seats_all_channel_all_partner = deployed_seats_all_channel_all_partner
        self.subscriptions_count = subscriptions_count
