# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1ServiceRequestOrganization(Model):
    """Describes the organization for which the service request is created.

    :param id: Gets or sets the unique identifier of the organization.
    :type id: str
    :param name: Gets or sets the name of the organization.
    :type name: str
    :param phone_number: Gets or sets the phone number of the organization.
    :type phone_number: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'phone_number': {'key': 'phoneNumber', 'type': 'str'},
    }

    def __init__(self, id=None, name=None, phone_number=None):
        super(MicrosoftPartnerSdkContractsV1ServiceRequestOrganization, self).__init__()
        self.id = id
        self.name = name
        self.phone_number = phone_number
