# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkInternalContractsAnalyticsCustomerDeploymentUsageInsight(Model):
    """Deployment and Usage insight for Customers of a Partner.

    :param customer_licenses_deployment_insight: Customer Licenses Deployment
     Insight
    :type customer_licenses_deployment_insight:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsAnalyticsCustomerLicensesDeploymentInsights
    :param customer_licenses_usage_insights: Collection of
     CustomerWorkloadUsageInsights
    :type customer_licenses_usage_insights:
     list[~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsAnalyticsCustomerLicensesUsageInsights]
    """

    _attribute_map = {
        'customer_licenses_deployment_insight': {'key': 'customerLicensesDeploymentInsight', 'type': 'MicrosoftPartnerSdkContractsAnalyticsCustomerLicensesDeploymentInsights'},
        'customer_licenses_usage_insights': {'key': 'customerLicensesUsageInsights', 'type': '[MicrosoftPartnerSdkContractsAnalyticsCustomerLicensesUsageInsights]'},
    }

    def __init__(self, customer_licenses_deployment_insight=None, customer_licenses_usage_insights=None):
        super(MicrosoftPartnerSdkInternalContractsAnalyticsCustomerDeploymentUsageInsight, self).__init__()
        self.customer_licenses_deployment_insight = customer_licenses_deployment_insight
        self.customer_licenses_usage_insights = customer_licenses_usage_insights
