# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1Contact(Model):
    """Describes contact information for a specific individual.

    :param first_name: Gets or sets the contact's first name.
    :type first_name: str
    :param last_name: Gets or sets the contact's last name.
    :type last_name: str
    :param email: Gets or sets the contact's email address.
    :type email: str
    :param phone_number: Gets or sets the contact's phone number.
    :type phone_number: str
    """

    _attribute_map = {
        'first_name': {'key': 'firstName', 'type': 'str'},
        'last_name': {'key': 'lastName', 'type': 'str'},
        'email': {'key': 'email', 'type': 'str'},
        'phone_number': {'key': 'phoneNumber', 'type': 'str'},
    }

    def __init__(self, first_name=None, last_name=None, email=None, phone_number=None):
        super(MicrosoftPartnerSdkContractsV1Contact, self).__init__()
        self.first_name = first_name
        self.last_name = last_name
        self.email = email
        self.phone_number = phone_number
