# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1InternalApplicationsApplication(Model):
    """Application.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param account_id: The account Id.
    :type account_id: str
    :param commerce_id: The commerce Id.
    :type commerce_id: str
    :param domain: The domain.
    :type domain: str
    :param object_id: The application object Id.
    :type object_id: str
    :param id: The application Id.
    :type id: str
    :param application_type: The application type. Possible values include:
     'none', 'native', 'web'
    :type application_type: str or
     ~microsoft.store.partnercenterservices.models.enum
    :param name: The application name.
    :type name: str
    :param identifier_uris: The identifier Uris.
    :type identifier_uris: list[str]
    :param credentials_uri: The uri to get the credentials of the application.
    :type credentials_uri: str
    :param resources: List of resources.
    :type resources:
     list[~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1InternalApplicationsApplicationResource]
    :param accessible_endpoints: The endpoints to which the apps has access.
    :type accessible_endpoints: list[str]
    :param authorization_uri: The consent Uri to complete the application
     authorization.
    :type authorization_uri: str
    :ivar attributes: Gets the attributes.
    :vartype attributes:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceAttributes
    """

    _validation = {
        'attributes': {'readonly': True},
    }

    _attribute_map = {
        'account_id': {'key': 'accountId', 'type': 'str'},
        'commerce_id': {'key': 'commerceId', 'type': 'str'},
        'domain': {'key': 'domain', 'type': 'str'},
        'object_id': {'key': 'objectId', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'application_type': {'key': 'applicationType', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'identifier_uris': {'key': 'identifierUris', 'type': '[str]'},
        'credentials_uri': {'key': 'credentialsUri', 'type': 'str'},
        'resources': {'key': 'resources', 'type': '[MicrosoftPartnerSdkContractsV1InternalApplicationsApplicationResource]'},
        'accessible_endpoints': {'key': 'accessibleEndpoints', 'type': '[str]'},
        'authorization_uri': {'key': 'authorizationUri', 'type': 'str'},
        'attributes': {'key': 'attributes', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceAttributes'},
    }

    def __init__(self, account_id=None, commerce_id=None, domain=None, object_id=None, id=None, application_type=None, name=None, identifier_uris=None, credentials_uri=None, resources=None, accessible_endpoints=None, authorization_uri=None):
        super(MicrosoftPartnerSdkContractsV1InternalApplicationsApplication, self).__init__()
        self.account_id = account_id
        self.commerce_id = commerce_id
        self.domain = domain
        self.object_id = object_id
        self.id = id
        self.application_type = application_type
        self.name = name
        self.identifier_uris = identifier_uris
        self.credentials_uri = credentials_uri
        self.resources = resources
        self.accessible_endpoints = accessible_endpoints
        self.authorization_uri = authorization_uri
        self.attributes = None
