# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftPartnerSdkContractsV1InternalPromotionsPromotion(Model):
    """Represents a collection of information related to promotion.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param id: Gets or sets the Id of the promotion.
    :type id: str
    :param name: Gets or sets the name of the promotion.
    :type name: str
    :param is_enabled: Gets or sets the is enabled property.
    :type is_enabled: bool
    :param offer_ids: Gets or sets the list of supported offer ids.
    :type offer_ids: list[str]
    :param countries: Gets or sets the list of support countries.
    :type countries: list[str]
    :param start_date: Gets or sets the start date of the promotion.
    :type start_date: datetime
    :param end_date: Gets or sets the end date of the promotion.
    :type end_date: datetime
    :param discount_type: Gets or sets the discount type of the promotion.
    :type discount_type: str
    :param discount_value: Gets or sets the discount value of the promotion.
    :type discount_value: float
    :param duration: Gets or sets the duration of the discount.
    :type duration: int
    :param duration_unit_of_measure: Gets or sets the term unit of measure of
     the discount. Possible values include: 'other', 'day', 'month', 'year'
    :type duration_unit_of_measure: str or
     ~microsoft.store.partnercenterservices.models.enum
    :param links: Gets or sets the links.
    :type links:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceLinks
    :ivar attributes: Gets the attributes.
    :vartype attributes:
     ~microsoft.store.partnercenterservices.models.MicrosoftPartnerSdkContractsV1CommonResourceAttributes
    """

    _validation = {
        'attributes': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'is_enabled': {'key': 'isEnabled', 'type': 'bool'},
        'offer_ids': {'key': 'offerIds', 'type': '[str]'},
        'countries': {'key': 'countries', 'type': '[str]'},
        'start_date': {'key': 'startDate', 'type': 'iso-8601'},
        'end_date': {'key': 'endDate', 'type': 'iso-8601'},
        'discount_type': {'key': 'discountType', 'type': 'str'},
        'discount_value': {'key': 'discountValue', 'type': 'float'},
        'duration': {'key': 'duration', 'type': 'int'},
        'duration_unit_of_measure': {'key': 'durationUnitOfMeasure', 'type': 'str'},
        'links': {'key': 'links', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceLinks'},
        'attributes': {'key': 'attributes', 'type': 'MicrosoftPartnerSdkContractsV1CommonResourceAttributes'},
    }

    def __init__(self, id=None, name=None, is_enabled=None, offer_ids=None, countries=None, start_date=None, end_date=None, discount_type=None, discount_value=None, duration=None, duration_unit_of_measure=None, links=None):
        super(MicrosoftPartnerSdkContractsV1InternalPromotionsPromotion, self).__init__()
        self.id = id
        self.name = name
        self.is_enabled = is_enabled
        self.offer_ids = offer_ids
        self.countries = countries
        self.start_date = start_date
        self.end_date = end_date
        self.discount_type = discount_type
        self.discount_value = discount_value
        self.duration = duration
        self.duration_unit_of_measure = duration_unit_of_measure
        self.links = links
        self.attributes = None
