# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SystemSecuritySecureString(Model):
    """SystemSecuritySecureString.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar length:
    :vartype length: int
    """

    _validation = {
        'length': {'readonly': True},
    }

    _attribute_map = {
        'length': {'key': 'length', 'type': 'int'},
    }

    def __init__(self):
        super(SystemSecuritySecureString, self).__init__()
        self.length = None
