# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SystemCollectionsGenericKeyValuePairSystemStringSystemString(Model):
    """SystemCollectionsGenericKeyValuePairSystemStringSystemString.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar key:
    :vartype key: str
    :ivar value:
    :vartype value: str
    """

    _validation = {
        'key': {'readonly': True},
        'value': {'readonly': True},
    }

    _attribute_map = {
        'key': {'key': 'key', 'type': 'str'},
        'value': {'key': 'value', 'type': 'str'},
    }

    def __init__(self):
        super(SystemCollectionsGenericKeyValuePairSystemStringSystemString, self).__init__()
        self.key = None
        self.value = None
