# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SystemCollectionsGenericKeyValuePairMicrosoftPartnerSdkContractsV1DeviceDeploymentPolicyCategorySystemString(Model):
    """SystemCollectionsGenericKeyValuePairMicrosoftPartnerSdkContractsV1DeviceDeploymentPolicyCategorySystemString.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar key: Possible values include: 'none', 'o_o_b_e'
    :vartype key: str or ~microsoft.store.partnercenterservices.models.enum
    :ivar value:
    :vartype value: str
    """

    _validation = {
        'key': {'readonly': True},
        'value': {'readonly': True},
    }

    _attribute_map = {
        'key': {'key': 'key', 'type': 'str'},
        'value': {'key': 'value', 'type': 'str'},
    }

    def __init__(self):
        super(SystemCollectionsGenericKeyValuePairMicrosoftPartnerSdkContractsV1DeviceDeploymentPolicyCategorySystemString, self).__init__()
        self.key = None
        self.value = None
